# 1. Basic Perceptron
 ---
### This ipynb, shows the basic implementation of a perceptron model, that can take in real valued inputs as inputs and weights, and aggregates them with a bias. It then passes it through an activation func, and gives the output.

In [14]:
import numpy as np
from tensorflow.keras import activations as act

In [10]:
input = np.random.uniform(1, 6, [3, 1])
print(input)

[[2.37904976]
 [2.54430123]
 [5.45800205]]


In [11]:
weights = np.random.uniform(2, 5, [3, 3])
print(weights)

[[4.88743187 4.48756724 2.62395713]
 [2.73196571 3.71690772 3.4214395 ]
 [4.62717226 4.85354047 4.32148228]]


In [12]:
bias = np.random.uniform(1, 3, [3, 1])
print(bias)

[[2.45277064]
 [1.48167057]
 [1.82878593]]


In [13]:
agg = np.dot(weights.T, input) + bias
print(agg)

[[46.28627368]
 [48.10538305]
 [40.36314236]]


In [18]:
yhat = np.array(act.selu(agg))
yhat

array([[48.63303346],
       [50.54437346],
       [42.40959353]])