# 2. Multi Layer Perceptron - Layer as an Object
---
### This is an object oriented implementation of the multilayer perceptron, with each layer as an object. The Layer implementation has been generalised, and a sepcific example of a 3 layer NN has been provided. This notebook only deals with the forward pass of the NN iteration.

In [96]:
import numpy as np
from tensorflow.keras import activations as act
import tensorflow as tf

In [5]:
def sig_der(arr):
    return arr * (1 - arr)

In [111]:
class Layer:
    def __init__(self, inp, wei, bias, output = False, outs = []):
        self.input = inp
        self.non = len(self.input)
        self.weights = wei
        self.bias = bias
        self.outs = outs
        self.output = output
        self.grad = []
        self.grads_next = []
    
    def __str__(self):
        return f"""
                \n\tNo. of nodes in layer = {self.non}
                \n\tInputs = {self.input}
                \n\tWeights = {self.weights}
                \n\tBias = {self.bias}
                """
    def calc_outs(self):
        agg = np.dot(self.weights.T, self.input) + self.bias
        if self.output == False:
            self.outs = np.array(act.sigmoid(agg))
        else:
            self.outs = np.array(act.softmax(tf.constant(agg)))
        return self.outs
    
    def pass_grads(self, arr):
        self.grads_next = arr
    
    def calc_grads(self):
        self.grads = sig_der(self.grads_next)
    
    def pass_grads_prev(self, prev_l):
        prev_l.pass_grads(prev_l, self.grad)
        

#### EXAMPLE

In [72]:
xin = np.random.uniform(1, 5, [2, 1])
bias0 = np.random.uniform(1, 4, [2, 1])
wei0 = np.random.uniform(3, 7, [2, 2])

l0 = Layer(xin, wei0, bias0)
print(l0)


                
	No. of nodes in layer = 2
                
	Inputs = [[1.91684303]
 [1.74563601]]
                
	Weights = [[4.63615256 4.94569195]
 [4.52213165 5.94552828]]
                
	Bias = [[2.04547624]
 [3.7307108 ]]
                


In [73]:
out0 = l0.calc_outs()
print(out0)

[[0.99999999]
 [1.        ]]


In [74]:
h1in = out0
bias1 = np.random.uniform(2, 3, [2, 1])
wei1 = np.random.uniform(0, 2, [2, 2])

l1 = Layer(h1in, wei1, bias1)
print(l1)


                
	No. of nodes in layer = 2
                
	Inputs = [[0.99999999]
 [1.        ]]
                
	Weights = [[0.48962699 1.07138888]
 [1.23759256 0.50923617]]
                
	Bias = [[2.88430179]
 [2.37166986]]
                


In [80]:
out1 = l1.calc_outs()
print(out1)

[[0.99016108]
 [0.98115153]]


In [112]:
out_in = out1
bias2 = np.random.uniform(0, 3, [1, 1])
wei2 = np.random.uniform(1, 2, [2, 2])

lout = Layer(out1, wei2, bias2, output = True)
print(lout)


                
	No. of nodes in layer = 2
                
	Inputs = [[0.99016108]
 [0.98115153]]
                
	Weights = [[1.45395512 1.48096459]
 [1.92434968 1.12992541]]
                
	Bias = [[2.17106813]]
                


In [113]:
output_final = lout.calc_outs()
print(output_final)

[[1.]
 [1.]]
